### ISSUE TITLE
(win32) ImportError: DLL load failed while importing _sqlite3

### ISSUE THREAD

**Issue by nfette** [coleifer/sqlcipher3#11]
I built the package using `python setup.py build_static build`, and installed with `python setup.py install`. However, then I get the error in my code:

```python
In [1]: import sqlcipher3
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import sqlcipher3

File ~\virtualenvs\dbstuff\lib\site-packages\sqlcipher3-0.4.5-py3.10-win-amd64.egg\sqlcipher3\__init__.py:23, in <module>
      1 # pysqlite2/__init__.py: the pysqlite2 package.
      2 #
      3 # Copyright (C) 2005 Gerhard Haring <gh@ghaering.de>
   (...)
     20 #    misrepresented as being the original software.
     21 # 3. This notice may not be removed or altered from any source distribution.
---> 23 from sqlcipher3.dbapi2 import *

File ~\virtualenvs\dbstuff\lib\site-packages\sqlcipher3-0.4.5-py3.10-win-amd64.egg\sqlcipher3\dbapi2.py:28, in <module>
     25 import time
     26 import collections.abc
---> 28 from sqlcipher3._sqlite3 import *
     30 paramstyle = "qmark"
     32 threadsafety = 1

ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.
```

To rule out possibility of missing a dependency at loading time, I see that this _sqlite3....pyd file is the "DLL" that gets bundled into the egg to install:
<pre>
./build
├───bdist.win-amd64
└───lib.win-amd64-3.10
    └───sqlcipher3
            dbapi2.py
            _sqlite3.cp310-win_amd64.pyd
            __init__.py
</pre>
and it appears to depend on these other DLLs, which are all visible in PATH environment variable when I start python:
- libcrypto-3-x64.dll from OpenSSL
- python310.dll from python (must not install python from Microsoft Store)

Sorry to bring another question from Windows 10. I am using python 3.10.3 and MSVC 2017. Any thoughts?

**Comment by coleifer** [comment]
No idea friend, sorry. I'd suggest stackoverflow.

**Comment by nfette** [comment]
Thank you, that worked. I poked around and found an answer about [python module dlls](https://stackoverflow.com/a/64303856). My libcrypto needed to be exposed differently, either:
* Add it in SYSTEM path, not just user path variable, or
* Execute this statement before importing sqlcipher3:
```python
import os
os.add_dll_directory('C:/install/OpenSSL-Win64/bin/')
```
This solved my problem.
