### ISSUE TITLE
Unable to use binary package

### ISSUE THREAD

**Issue by infosisio** [coleifer/sqlcipher3#13]
I am on Ubuntu 20.04 (Python 3.8.10) and unable to get the self contained binary to work with the following errors showing up after installing it via pip and running the application:

> sqlcipher3.dbapi2.DatabaseError: file is not a database
> peewee.DatabaseError: file is not a database

I can get it to work by building it manually - let me know if there's anything more I can supply.

**Comment by coleifer** [comment]
It seems OK to me.

In one virtualenv I installed sqlcipher3-binary, and in another sqlcipher3. I then ran the following script in one environment:

```python
from sqlcipher3 import dbapi2 as sqlcipher
conn = sqlcipher.connect('/tmp/test.db')
conn.execute("pragma key='testkey'")
conn.execute('create table kv("key" text not null)')
conn.execute('insert into kv ("key") values (?), (?), (?)', ('k1', 'k2', 'k3'))
conn.commit()
print(conn.execute('select * from kv').fetchall())
```

In the other environment I ran:

```python
from sqlcipher3 import dbapi2 as sqlcipher
conn = sqlcipher.connect('/tmp/test.db')
conn.execute("pragma key='testkey'")
print(conn.execute('select * from kv').fetchall())
```

In both cases the database was readable and writable by both environments.

**Comment by coleifer** [comment]
You might also try checking that the values of these pragmas are the same between versions: https://www.zetetic.net/sqlcipher/sqlcipher-api/#Default_PRAGMAs
