### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by fshort** [coleifer/sqlcipher3#17]
Followed the instructions to clone then build but am getting this error when I try to import in the python shell:
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlcipher3 import dbapi2 as sqlcipher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sqlcipher3/sqlcipher3/__init__.py", line 23, in <module>
    from sqlcipher3.dbapi2 import *
  File "/home/sqlcipher3/sqlcipher3/dbapi2.py", line 28, in <module>
    from sqlcipher3._sqlite3 import *
ModuleNotFoundError: No module named 'sqlcipher3._sqlite3'

Is some dependency missing from the build?

**Comment by coleifer** [comment]
You are missing the C extension.
