### ISSUE TITLE
M1 Mac install issues

### ISSUE THREAD

**Issue by dadrake3** [coleifer/sqlcipher3#21]
having issues installing this from source on an M1 Mac

running python setup.py build seems to fail silently, it just outputs

```
running build
running build_py
running build_ext
Builds a C extension linking against libsqlcipher library
```

and then python setup.py install succeeds but I get 

```
>>> import sqlcipher3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daryldrake/sandbox/repos/sqlcipher3/sqlcipher3/__init__.py", line 23, in <module>
    from sqlcipher3.dbapi2 import *
  File "/Users/daryldrake/sandbox/repos/sqlcipher3/sqlcipher3/dbapi2.py", line 28, in <module>
    from sqlcipher3._sqlite3 import *
ModuleNotFoundError: No module named 'sqlcipher3._sqlite3'
```

I tried using arm and x86 home-brew installs of sqlcipher with arm / x86 conda envs

**Comment by coleifer** [comment]
It should compile as long as you have the python headers and libsqlcipher installed. Guessing you're missing one of those?

**Comment by dadrake3** [comment]
I have sqlcipher installed from brew and I have the header files, as such im able to successfully build and install pysqlcipher3 but not sqlcipher3

**Comment by dadrake3** [comment]
when I run setup.py build --force I get the following output

running build
running build_py
copying sqlcipher3/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-311/sqlcipher3
copying sqlcipher3/dbapi2.py -> build/lib.macosx-10.9-x86_64-cpython-311/sqlcipher3
running build_ext
Builds a C extension linking against libsqlcipher library
building 'sqlcipher3._sqlite3' extension
clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -Qunused-arguments -DMODULE_NAME=\"sqlcipher3.dbapi2\" -I/usr/include -I/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include/python3.11 -c src/blob.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/blob.o
clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -Qunused-arguments -DMODULE_NAME=\"sqlcipher3.dbapi2\" -I/usr/include -I/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include/python3.11 -c src/cache.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/cache.o
clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -Qunused-arguments -DMODULE_NAME=\"sqlcipher3.dbapi2\" -I/usr/include -I/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include/python3.11 -c src/connection.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/connection.o
clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -Qunused-arguments -DMODULE_NAME=\"sqlcipher3.dbapi2\" -I/usr/include -I/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include/python3.11 -c src/cursor.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/cursor.o
clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -Qunused-arguments -DMODULE_NAME=\"sqlcipher3.dbapi2\" -I/usr/include -I/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include/python3.11 -c src/microprotocols.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/microprotocols.o
clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -Qunused-arguments -DMODULE_NAME=\"sqlcipher3.dbapi2\" -I/usr/include -I/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include/python3.11 -c src/module.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/module.o
clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -Qunused-arguments -DMODULE_NAME=\"sqlcipher3.dbapi2\" -I/usr/include -I/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include/python3.11 -c src/prepare_protocol.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/prepare_protocol.o
clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -Qunused-arguments -DMODULE_NAME=\"sqlcipher3.dbapi2\" -I/usr/include -I/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include/python3.11 -c src/row.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/row.o
clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -Qunused-arguments -DMODULE_NAME=\"sqlcipher3.dbapi2\" -I/usr/include -I/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include/python3.11 -c src/statement.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/statement.o
clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include -Qunused-arguments -DMODULE_NAME=\"sqlcipher3.dbapi2\" -I/usr/include -I/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/include/python3.11 -c src/util.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/util.o
clang -bundle -undefined dynamic_lookup -Wl,-rpath,/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/lib -L/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/lib -Wl,-rpath,/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/lib -L/opt/homebrew/Caskroom/miniconda/base/envs/rekordbox/lib -Qunused-arguments build/temp.macosx-10.9-x86_64-cpython-311/src/blob.o build/temp.macosx-10.9-x86_64-cpython-311/src/cache.o build/temp.macosx-10.9-x86_64-cpython-311/src/connection.o build/temp.macosx-10.9-x86_64-cpython-311/src/cursor.o build/temp.macosx-10.9-x86_64-cpython-311/src/microprotocols.o build/temp.macosx-10.9-x86_64-cpython-311/src/module.o build/temp.macosx-10.9-x86_64-cpython-311/src/prepare_protocol.o build/temp.macosx-10.9-x86_64-cpython-311/src/row.o build/temp.macosx-10.9-x86_64-cpython-311/src/statement.o build/temp.macosx-10.9-x86_64-cpython-311/src/util.o -L/usr/lib -lsqlcipher -o build/lib.macosx-10.9-x86_64-cpython-311/sqlcipher3/_sqlite3.cpython-311-darwin.so
ld: warning: dylib (/usr/local/Cellar/sqlcipher/4.5.5/lib/libsqlcipher.dylib) was built for newer macOS version (13.0) than being linked (10.9)

**Comment by coleifer** [comment]
No idea bro, might try taking it to the genius bar.

Although I do see it looks like you're building for Mac OS X 10.9 while libsqlcipher was built for 10.13 or newer? Possibly to do with the way your python environment is set-up. You may need to build libsqlcipher inside your 10.9 miniconda environment or whatever I honestly have no idea it looks like Greek to me.

**Comment by dadrake3** [comment]
I fixed it by adding these symlinks

```
ln -s /opt/homebrew/lib/libsqlcipher.a /usr/local/lib/libsqlcipher.a
ln -s /opt/homebrew/include/sqlcipher /usr/local/include/sqlcipher
```
