### ISSUE TITLE
ImportError: symbol not found in flat namespace '_ERR_error_string'

### ISSUE THREAD

**Issue by NiklasWyld** [coleifer/sqlcipher3#25]
I'm trying to use sqlcipher3 on my mac. I've installed SQLCipher using Homebrew and the sqlcipher3 Python package via pip. However, when I attempt to import sqlcipher3 using the following code:

from sqlcipher3 import dbapi2

I encounter the following error:

ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sqlcipher3-0.5.2-py3.10-macosx-10.9-universal2.egg/sqlcipher3/_sqlite3.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_ERR_error_string' 

Here are the steps I've followed so far:

Installed SQLCipher using Homebrew:

brew install sqlcipher

Installed sqlcipher3 using pip:

pip install sqlcipher3

Reinstalled sqlcipher3:

pip install --no-cache-dir --force-reinstall sqlcipher3

Despite these steps, I still receive the ImportError mentioned above.

**Comment by coleifer** [comment]
Are you able to run `sqlcipher` via the command line at all? That looks to be an openssl symbol, so maybe some issue there.

At any rate, I don't know my way around "mac" "os" lol so I'm not going to be of much help.
