### ISSUE TITLE
Error: file is encrypted or is not a database

### ISSUE THREAD

**Issue by franck-serot** [coleifer/sqlcipher3#8]
Hi,
I created a simple Python app with

Flask==2.0.1
Flask-SQLAlchemy==2.5.1
SQLAlchemy==1.4.22
sqlcipher3-binary==0.4.5
and the configuration
BASEDIR = os.path.abspath(os.path.dirname(file))
SQLALCHEMY_DATABASE_URI = 'sqlite+pysqlcipher://:passphrase@/' + BASEDIR + '/db1.sqlite'
I tries to use sqlcipher 3.15.2 in order to check the content of the database with or without a passphrase.

Without the passphrase, the database is not ciphered and I can show the schema of the database for example.
With the passphrase, I defined the passphrase with the pragma command "PRAGMA key='passphrase';" but sqlcipher returns the following error :
Error: file is encrypted or is not a database

I tried cipher a base directly with sqlcipher and I'm able to check the passphrase without no problem.

Would you please helpl me to understand the problem and solve it ?
Best regards,
Franck

**Comment by franck-serot** [comment]
For information, I have tried already to create an issue on the project sqlalchemy.
https://github.com/sqlalchemy/sqlalchemy/issues/6820

**Comment by coleifer** [comment]
There is nothing wrong with sqlcipher or the python bindings. Here I create an encrypted database via python, and then access it using the shell:

![sqlcipher](https://user-images.githubusercontent.com/119974/127339650-2a3455a5-3f4e-4117-8111-303e7135365f.png)

**Comment by franck-serot** [comment]
Yes I had done this test but when the database was creatd by sqlalchmy then sqlcipher can't uncipher the database.
could you please try this tests in your side ?
